use_frameworks!

platform :ios, '9.0'

target 'CBIBlinkingLabel_Example' do
  pod 'CBIBlinkingLabel', :path => '../'

  target 'CBIBlinkingLabel_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
